window.YT_V2_TEMPLATES = [
  {
    id: "trend_to_revenue",
    code: "T1",
    name: "Breaking AI News",
    shortName: "AI News",
    description: "Turn a model release or platform update into a commercially useful AI UGC test.",
    audience: "Broad discovery",
    color: "#ff6b4a",
    icon: "bolt",
    editorPreset: "Fast news",
    thumbnailPreset: "Model + result",
    requiredAssets: ["A-roll", "Model screen recording", "Generated outputs"],
    match: ["new", "launch", "released", "update", "introducing", "seedance", "veo", "runway", "kling", "sora"],
    sections: [
      ["Cold open + finished result", 120],
      ["What was released", 250],
      ["Why brands and affiliates should care", 300],
      ["Test setup and success criteria", 250],
      ["Live demonstration", 750],
      ["Output analysis", 350],
      ["ViralView workflow", 300],
      ["Verdict", 100],
      ["Call to action", 80],
    ],
  },
  {
    id: "model_battle",
    code: "T2",
    name: "Model Battle",
    shortName: "Comparison",
    description: "Compare two or more tools using the same product, prompt, and commercial scorecard.",
    audience: "Search + buyer intent",
    color: "#7758ff",
    icon: "compare",
    editorPreset: "Comparison scorecard",
    thumbnailPreset: "Versus",
    requiredAssets: ["A-roll", "Output A", "Output B", "Screen recordings"],
    match: [" vs ", "best", "compare", "comparison", "tested", "tools"],
    sections: [
      ["Competing results", 120],
      ["Stakes and viewer problem", 180],
      ["Test methodology", 250],
      ["Model A", 450],
      ["Model B", 450],
      ["Scorecard", 300],
      ["Winner inside ViralView", 400],
      ["Recommendation", 200],
      ["Call to action", 150],
    ],
  },
  {
    id: "winner_teardown",
    code: "T3",
    name: "Winning Video Teardown",
    shortName: "Teardown",
    description: "Reverse-engineer the hook, pacing, proof, reveal, offer, and CTA without copying the source.",
    audience: "Strategy authority",
    color: "#00a8ff",
    icon: "layers",
    editorPreset: "Annotated teardown",
    thumbnailPreset: "Why it sold",
    requiredAssets: ["A-roll", "Source excerpts", "Annotated screenshots"],
    match: ["why", "viral", "winning", "sold", "mistakes", "fake", "works"],
    sections: [
      ["Hook recreation", 100],
      ["Product and audience context", 250],
      ["Source summary", 150],
      ["Beat-by-beat breakdown", 900],
      ["Why it converts", 300],
      ["Three original remixes", 400],
      ["Build one in ViralView", 300],
      ["Call to action", 100],
    ],
  },
  {
    id: "brand_build",
    code: "T4",
    name: "Brand Build-With-Me",
    shortName: "Brand Build",
    description: "Build a complete product-specific AI UGC campaign from a proven creative structure.",
    audience: "Brands + agencies",
    color: "#0bba7a",
    icon: "wand",
    editorPreset: "Clean build",
    thumbnailPreset: "Before / after",
    requiredAssets: ["A-roll", "ViralView screen recording", "Product assets", "Generated clips"],
    match: ["how to", "workflow", "build", "create", "tutorial", "campaign", "ads"],
    sections: [
      ["Finished result", 120],
      ["Brand brief", 230],
      ["Source analysis", 350],
      ["Creative angles", 300],
      ["Script development", 400],
      ["Scenes and character", 400],
      ["Generate, edit, export", 350],
      ["Testing plan", 200],
      ["Call to action", 150],
    ],
  },
  {
    id: "affiliate_factory",
    code: "T5",
    name: "TikTok Shop Affiliate",
    shortName: "Affiliate",
    description: "Turn one product and proven format into a week of original affiliate content.",
    audience: "TikTok Shop affiliates",
    color: "#ff3d82",
    icon: "shop",
    editorPreset: "TikTok product",
    thumbnailPreset: "Product + quantity",
    requiredAssets: ["A-roll", "Product page", "Product media", "Vertical outputs"],
    match: ["tiktok", "shop", "affiliate", "product", "faceless", "commission"],
    sections: [
      ["Hook and finished videos", 120],
      ["Product selection", 250],
      ["Audience and angle research", 300],
      ["Structural references", 250],
      ["Hook generation", 350],
      ["Three scripts", 450],
      ["Generate and edit", 350],
      ["Posting plan", 250],
      ["Disclosure reminder", 100],
      ["Call to action", 80],
    ],
  },
  {
    id: "experiment_case_study",
    code: "T6",
    name: "Experiment / Case Study",
    shortName: "Experiment",
    description: "Document a real challenge with transparent rules, costs, failures, and measurable results.",
    audience: "Proof + conversion",
    color: "#e3a008",
    icon: "flask",
    editorPreset: "Results documentary",
    thumbnailPreset: "Result + number",
    requiredAssets: ["A-roll", "Process footage", "Cost data", "Results"],
    match: ["i made", "i spent", "days", "results", "challenge", "experiment", "case study"],
    sections: [
      ["Result-first hook", 120],
      ["Hypothesis", 180],
      ["Rules and metric", 200],
      ["Test setup", 250],
      ["Creative production", 500],
      ["Test execution", 350],
      ["Results", 450],
      ["Lessons", 250],
      ["Next iteration", 120],
      ["Call to action", 80],
    ],
  },
];
